### ISSUE TITLE
Keeping images with models

### ISSUE THREAD

**Issue by Evidlo** [thanethomson/statik#116]
I'd like to proposal an alternate structure for model instances so that any resources (images, etc.) can stay in the same directory.

A simple example is given below

```
data/
    projects/
        foo_proj.md            <-- standard model instance
        bar_proj/              <-- model instance with resources
            project.md
            image1.png
            image2.png        
```
`views/project.yml`
```
path:
  template: /projects/{{ project.slug }}
  resources: /projects/{{ project.slug }}     <-- output directory for model resources
  for-each:
    project: session.query(Project).all()
template: project
context:
  dynamic:
```

This would yield the following output
```
public/
    projects/
        foo_proj/
            index.html
        bar_proj/
            index.html
            image1.png
            image2.png
```
