### ISSUE TITLE
Make it possible to reuse a view

### ISSUE THREAD

**Issue by dennohpeter** [thanethomson/statik#118]
I think it would be nice to make it possible to reuse a specific view from different templates i.e  **more details view**.
Example:
On my case I have
* Programmes template
* current projects template
* ...etc
Models
* Programmes
* CurrentProjects

Each model has multiple items each with it own more-info-link and  they will  both be reusing the same moreinfo template
Am finding it repetitive to generate same view structure but with different model to be referenced in the templates above.

So my suggestion was, it would be nice if the next release{before the breaking change  :point_right: } #109  would make it possible to reuse a view something like this on templates on each loop
```
## programmes template
<a href="{% url 'moreDetails', programmes %}" class="btn
              btn-primary btn-outline-theme">Read More</a>
```
```
## currentProjects template
<a href="{% url 'moreDetails', currentProjects %}" class="btn
              btn-primary btn-outline-theme">Read More</a>
```
Through the following approache: 
* only changing model name and generating the corresponding the path templates
```
path:
  template: /{{ post.read_more_link }}/
  for-each: 
    post: session.query(**SomeplaceholderModelName**).all()
template: moreDetails
```
* add support for multiple paths on the same view
```
path:
  template: /{{ post.read_more_link }}/
  for-each: 
    post: session.query(Programmes).all()
path:
  template: /{{ post.read_more_link }}/
  for-each: 
    post: session.query(CurrentProjects).all()
template: moreDetails
```
* make it possible for session.query(Model1, Model2, Model2, ..etc) to query multiple Models and return the as list which can be later be used to make multiple template paths
* and any other better way :smiley:
