### ISSUE TITLE
TypeError: count() takes exactly one argument (0 given)

### ISSUE THREAD

**Issue by dennohpeter** [thanethomson/statik#120]
I got that error while using paginate
here is my views 
```
path:
  template: /posts/{{ page }}
  for-each: 
    page: paginate(session.query(Programmes).all(), 1)
template: moreDetails
```
and here is what `db_query` looks in in
Paginator class 
line 100
`[<statik.database.Programmes object at 0x7f2734e2be90>, <statik.database.Programmes object at 0x7f2734e2bf10>, <statik.database.Programmes object at 0x7f2734e2bf90>]`

can open I open a pull request to resolve the error by  using `len` instead of `count`?
`self.total_items = len(db_query) - offset`

**Comment by dennohpeter** [comment]
My bad, I realized 
```
path:
  template: /posts/{{ page }}
  for-each: 
    page: paginate(session.query(Programmes).all(), 1)
template: moreDetails
```
There shouldn't be .all() in the query, mention that in the docs maybe
