### ISSUE TITLE
sqlalchemy.exc.NoForeignKeysError while watching a folder with empty model file

### ISSUE THREAD

**Issue by thanethomson** [thanethomson/statik#19]
I get the following exception while watching a folder (when it reloads the content for the first time after changing a file):

```
sqlalchemy.exc.NoForeignKeysError: Could not determine join condition between parent/child tables on relationship Post.tags - there are no foreign keys linking these tables via secondary table 'PostTag'.  Ensure that referencing columns are associated with a ForeignKey or ForeignKeyConstraint, or specify 'primaryjoin' and 'secondaryjoin' expressions.
```

where `Post.yml` looks as follows:
```yaml
title: String
slug: String
summary: Text
date: DateTime
tags: Tag[] -> posts
content: Content
```

and `Tag.yml` is empty (i.e. only a `pk` field).
