### ISSUE TITLE
Batteries-included RSS/Atom feed support

### ISSUE THREAD

**Issue by thanethomson** [thanethomson/statik#23]
RSS/Atom feeds should be generated automatically from configuration options in the project's `config.yml` file.

e.g.

```yaml
project-name: RSS demo project
base-path: /
feeds:
  posts:
    file: /feeds/posts.xml
    query: session.query(Post).order_by(Post.date.desc())
  projects:
    file: /feeds/projects.xml
    query: session.query(Project).order_by(Project.released.desc())
```

**Comment by konstruktiv** [comment]
Wouldn't this only create a feed for all posts/projects/etc? How could we get feeds for more specific queries, such as all posts of a certain category or with a certain tag?

**Comment by thanethomson** [comment]
That particular example would get all posts and projects, but to make it more specific, just tweak your SQLAlchemy/MLAlchemy query that generates the feed.

e.g.

```yaml
feeds:
  programming-posts:
    file: /feeds/programming-posts.xml
    query: session.query(Post).filter(Post.tags.any(name='programming')).order_by(Post.date.desc())
```

See [SQLAlchemy's documentation](http://docs.sqlalchemy.org/en/latest/orm/tutorial.html#building-a-many-to-many-relationship) for details.
