### ISSUE TITLE
Allow importing python modules for dynamic context

### ISSUE THREAD

**Issue by Alxe** [thanethomson/statik#30]
Use case: Having a project-wide `compilation-date` for template usage.

```yaml
context:
  dynamic:
    compliation-date: from datetime import date; date.today().isoformat()
```

```jinja
<section id="footer_generated_on">
	<span>Generated on {{ compilation_date }}</span>
</section>
```

If done with a custom jinja tag, the date would be generated each time called.
