### ISSUE TITLE
Acces for-each context from model linked via fk

### ISSUE THREAD

**Issue by tombreit** [thanethomson/statik#43]
Hi, 
I have an `Album` and a `Photo` model, each Photo has a FK to the corresponding album. In my `album.yml`-view I set a for-each-context for a `photos_count` property:

```
path:
  template: /album/{{ album.pk }}
  for-each:
    album: session.query(Album).all()
template: album
context:
  for-each:
    photos: session.query(Photo).filter(Photo.album == album).all()
    geo_refs: list(map(list, list(session.query(Photo).filter(Photo.album == album).values('name', 'geo_lat', 'geo_lon'))))
    photos_count: session.query(Photo).filter(Photo.album == album).count()
```
Now I would like to access this property `photos.count` also in my `photo.html` template: 

`{{ photo.album.name }} / {{ photo.album.photos_count }} photos`

... but this will not work out of the box. 

Any Ideas how to inject the `photos_count` per album  in the photo template without code duplication?

PS: Please let my know if your issue tracker is not the right place for my questions - if only there would exist a stackoverflow `Statik`-tag...
