### ISSUE TITLE
{% url  %} Template tag always adds trailing slash

### ISSUE THREAD

**Issue by tombreit** [thanethomson/statik#48]
I'm generating a json file with a dedicated view 

```
# view/search_index.yml
path: /tipuesearch_content.js
template: tipuesearch_content
context:
  dynamic:
    photos: session.query(Photo).all()
```

and would like to link to the generated file (here: `public/tipuesearch_content.js`) with the [url template tag](https://github.com/thanethomson/statik/wiki/Jinja2-templates#-url-view-name-optional_param-): 

```
# templates/
<script src="{% url 'search_index' %}"></script> 
```

I expected a generated string like: 
`<script src="/tipuesearch_content.js"></script>`
but I got 
`<script src="/tipuesearch_content.js/"></script>`

How can I get rid of this trailing slash?
