### ISSUE TITLE
Buit-in webserver injects path segments when accessing correct rendered {% url %}

### ISSUE THREAD

**Issue by tombreit** [thanethomson/statik#49]
I get unexpected urls when accessing the site through the built-in webserver, but the html is rendered correct: 

 in | out  
------------ | -------------
**template** | ``{% url 'album' album %}``
**html** |  ``/projects/json2statik/album/eguelshardt-elsass``
**built-in webserver** | ``http://localhost:8000/projects/json2tt/album/album/eguelshardt-elsass/``

The ``/projects/json2statik`` is defined as ``base-path``. 

On the production site it's just fine: the url ``/projects/json2statik/album/eguelshardt-elsass`` took me to the expected ressource ``/projects/json2statik/album/eguelshardt-elsass`` - but with the built-in webserver I get redirected to ``http://localhost:8000/projects/json2statik/album/album/eguelshardt-elsass/`` - where does this duplication of ``album`` came from? Any tips or hints?

## Involved  views

I link from ``album_tile_index.yml``:
```
# views/album_tile_index.yml
path: /albums/browse
template: album_tile_index
context:
  dynamic:
    albums: session.query(Album).order_by(Album.sort_by.desc())
```
to ``album.yml``:
```
# views/album.yml
path:
  template: /album/{{ album.pk }}
  for-each:
    album: session.query(Album).all()
template: album
```
