### ISSUE TITLE
Unable to set a link via {% url %} to a specific instance

### ISSUE THREAD

**Issue by tombreit** [thanethomson/statik#51]
I have a model for regular pages which are used for things like *Contact*, *About* etc. defined in the following `view`: 

```
# views/page.yml
path:
  template: /{{ page.slug }}  
  for-each:
    page: session.query(Page).all()
template: page
```

and the following `data`:
```
# data/Page/contact.md
---
title: Contact
slug: contact
---
```

How do I generate a link to an instance of `page`?

I tried `{% url 'page', contact' %}`, but that does not generate the expected href `/contact/`. 

If I loop loop over a dynamic context variable in which all `Page` objects are stored, links get rendered as expected: 

```
# views/someview.yml
context:
  dynamic:
    static_pages: session.query(Page).all()
```

```
# templates/sometemplate.html
{% for page in static_pages %}
  * {% url 'page', page %}
{% endfor %}
```

**Comment by thanethomson** [comment]
The reason for this is that the `{% url %}` tag takes an object as its parameter to do a reverse lookup. What I'd recommend is trying something like the following:

```yaml
# views/someview.yml
context:
  dynamic:
    static_pages: dict([(page.slug, page) for page in session.query(Page).all()])
```

And then, in your template:

```html+jinja2
<a href="{% url 'page', static_pages.contact %}">{{ page.title }}</a>
```

**Comment by thanethomson** [comment]
Have you perhaps tried this out?

**Comment by tombreit** [comment]
Sorry for this late response - I was stuck with this proposed solution until I moved your query snippet from my ``config.yml`` to a ``view.yml``.

I had to tweak the template snippet: 

````
<a href="{% url 'page', home_static_pages.contact %}">{{ home_static_pages.contact.title }}</a>
````

Did you have an idea why this snippet does not work when stored in a project ``config.yml``:

````
# config.yml
project-name: myproject
context:
  dynamic:
    static_pages: dict([(page.slug, page) for page in session.query(Page).all()])
````

?
