### ISSUE TITLE
How to access a variable defined in config.py in a view?

### ISSUE THREAD

**Issue by tombreit** [thanethomson/statik#54]
Hi, 

I would like to store a project wide variable in my ``config.py``:

```
# config.py
project-name: myproject
context:
  static:
    my_threshold: 270
```

... and use this variable (here: ``my_threshold``) in some views: 

```
# views/foo.py
path: /foo
context:
  dynamic:
    render_elem: True if session.query(Bar).count() <= my_threshold else False
```

but accessing the variable seems not to be defined. 

Is something like this possible?
