### ISSUE TITLE
Support for syntax highlighting output in Markdown

### ISSUE THREAD

**Issue by thanethomson** [thanethomson/statik#6]
One of the major features of blog-oriented static website generators is to provide syntax highlighting. This could be accomplished client-side with the inclusion of certain libraries such as [highlight.js](https://highlightjs.org/), but one would also need support for server-side rendering, such as that provided by [Pygments](http://pygments.org/).

**Comment by NZSmartie** [comment]
I'm investigating a way to do this. 
From a quick glance, https://github.com/thanethomson/statik/blob/master/statik/templating.py#L230 has a fixed set of extensions being loaded for jinja2. 

jinja2-highlight needs to be included in that set of extensions. The best way I'm assuming would be to add additional config to `config.yml` for example

```yml
project-name: Hello World!
base-path: /
jinja2:
  extensions: 
    - jinja2_highlight.HighlightExtension
```
The rest should be simple after that

I'll create a PR soon if I can get this idea to work.
