### ISSUE TITLE
Split output file in chunks

### ISSUE THREAD

**Issue by tombreit** [thanethomson/statik#71]
In order to generate a valid google sitemap file, I need to split the file in chunks of a certain size (containing not more than 50.000 items): 

> Break up large sitemaps into a smaller sitemaps to prevent your server from being overloaded if Google requests your sitemap frequently. A sitemap file can't contain more than 50,000 URLs and must be no larger than 50 MB uncompressed.
(Source: https://support.google.com/webmasters/answer/183668?hl=en#general-guidelines)

Currently my simple view, rendering an "all-in" sitemaps file, which holds more than 50.000 items:
```
path: /google_image_sitemap.xml
template: google_image_sitemap.xml.jinja2
context:
  dynamic:
    photos: session.query(Photo).all()
```

I'm not aware of an elegant, "statik-esque" way of generating these chunks and link them in a (small) sitemaps-index-file. Any idea?
