### ISSUE TITLE
Add enum datatype

### ISSUE THREAD

**Issue by jayvdb** [thanethomson/statik#75]
Currently an enum needs to be constructed using a model with a LOV in the data.
That isnt a problem, however it isnt easy to use it like an enum in the templates.

Either literals need to be used:

`{% if item.foo == 'literal_string1' %}` or `{% if item.foo == 1 %}`

Or the view needs to explicitly import the enum model.
```yaml
context:
  dynamic:
    enum_value_1: session.query(EnumType).filter(EnumType.name == 'value_1').one().name
    enum_value_2: session.query(EnumType).filter(EnumType.name == 'value_2').one().name
```

Ideally the enum identifiers would be implicitly added to the template globals, so that the following syntax is possible without any extra voodoo.

`{% if item.foo == enum_name_identifier %}` or `{% if item.foo is enum_name.identifier %}`
